services:
  postgres:
    image: 'bitnami/postgresql:16.4.0'
    environment:
      - 'POSTGRESQL_DATABASE=theraven'
      - 'POSTGRESQL_PASSWORD=secret'
      - 'POSTGRESQL_USERNAME=user'
      - 'POSTGRESQL_POSTGRES_PASSWORD=secret'
    ports:
      - '15432:5432'
    volumes:
      - 'D:\theraven:/bitnami/postgresql'
